services:
  compiler-backend:
    build:
      context: ./compiler-backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - API_BASE_PATH=/api/compiler
      - HOST_WORKSPACE_ROOT=D:/SafeExam/Safe_Exam/compiler-backend/workspaces
      - COMPILER_SERVICE_KEY=${COMPILER_SERVICE_KEY:-safeexam-internal-compiler-key}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./compiler-backend/workspaces:/workspaces
    networks:
      - compiler-network

networks:
  compiler-network:
    driver: bridge
